services:
  # Gateway factories

  akanunov_easy_sms.gateway_factory.aliyun:
    class: Akanunov\EasySmsBundle\DependencyInjection\Factory\Gateway\AliyunFactory
    tags:
      - { name: akanunov_easy_sms.gateway_factory }

  akanunov_easy_sms.gateway_factory.aliyunrest:
    class: Akanunov\EasySmsBundle\DependencyInjection\Factory\Gateway\AliyunrestFactory
    tags:
      - { name: akanunov_easy_sms.gateway_factory }

  akanunov_easy_sms.gateway_factory.avatardata:
    class: Akanunov\EasySmsBundle\DependencyInjection\Factory\Gateway\AvatardataFactory
    tags:
      - { name: akanunov_easy_sms.gateway_factory }

  akanunov_easy_sms.gateway_factory.baidu:
    class: Akanunov\EasySmsBundle\DependencyInjection\Factory\Gateway\BaiduFactory
    tags:
      - { name: akanunov_easy_sms.gateway_factory }

  akanunov_easy_sms.gateway_factory.chuanglan:
    class: Akanunov\EasySmsBundle\DependencyInjection\Factory\Gateway\ChuanglanFactory
    tags:
      - { name: akanunov_easy_sms.gateway_factory }

  akanunov_easy_sms.gateway_factory.errorlog:
    class: Akanunov\EasySmsBundle\DependencyInjection\Factory\Gateway\ErrorlogFactory
    tags:
      - { name: akanunov_easy_sms.gateway_factory }

  akanunov_easy_sms.gateway_factory.huawei:
    class: Akanunov\EasySmsBundle\DependencyInjection\Factory\Gateway\HuaweiFactory
    tags:
      - { name: akanunov_easy_sms.gateway_factory }

  akanunov_easy_sms.gateway_factory.huaxin:
    class: Akanunov\EasySmsBundle\DependencyInjection\Factory\Gateway\HuaxinFactory
    tags:
      - { name: akanunov_easy_sms.gateway_factory }

  akanunov_easy_sms.gateway_factory.huyi:
    class: Akanunov\EasySmsBundle\DependencyInjection\Factory\Gateway\HuyiFactory
    tags:
      - { name: akanunov_easy_sms.gateway_factory }

  akanunov_easy_sms.gateway_factory.juhe:
    class: Akanunov\EasySmsBundle\DependencyInjection\Factory\Gateway\JuheFactory
    tags:
      - { name: akanunov_easy_sms.gateway_factory }

  akanunov_easy_sms.gateway_factory.luosimao:
    class: Akanunov\EasySmsBundle\DependencyInjection\Factory\Gateway\LuosimaoFactory
    tags:
      - { name: akanunov_easy_sms.gateway_factory }

  akanunov_easy_sms.gateway_factory.qcloud:
    class: Akanunov\EasySmsBundle\DependencyInjection\Factory\Gateway\QcloudFactory
    tags:
      - { name: akanunov_easy_sms.gateway_factory }

  akanunov_easy_sms.gateway_factory.rongcloud:
    class: Akanunov\EasySmsBundle\DependencyInjection\Factory\Gateway\RongcloudFactory
    tags:
      - { name: akanunov_easy_sms.gateway_factory }

  akanunov_easy_sms.gateway_factory.sendcloud:
    class: Akanunov\EasySmsBundle\DependencyInjection\Factory\Gateway\SendcloudFactory
    tags:
      - { name: akanunov_easy_sms.gateway_factory }

  akanunov_easy_sms.gateway_factory.submail:
    class: Akanunov\EasySmsBundle\DependencyInjection\Factory\Gateway\SubmailFactory
    tags:
      - { name: akanunov_easy_sms.gateway_factory }

  akanunov_easy_sms.gateway_factory.tianyiwuxian:
    class: Akanunov\EasySmsBundle\DependencyInjection\Factory\Gateway\TianyiwuxianFactory
    tags:
      - { name: akanunov_easy_sms.gateway_factory }

  akanunov_easy_sms.gateway_factory.twilio:
    class: Akanunov\EasySmsBundle\DependencyInjection\Factory\Gateway\TwilioFactory
    tags:
      - { name: akanunov_easy_sms.gateway_factory }

  akanunov_easy_sms.gateway_factory.yunpian:
    class: Akanunov\EasySmsBundle\DependencyInjection\Factory\Gateway\YunpianFactory
    tags:
      - { name: akanunov_easy_sms.gateway_factory }

  akanunov_easy_sms.gateway_factory.yuntongxun:
    class: Akanunov\EasySmsBundle\DependencyInjection\Factory\Gateway\YuntongxunFactory
    tags:
      - { name: akanunov_easy_sms.gateway_factory }

  akanunov_easy_sms.gateway_factory.yunxin:
    class: Akanunov\EasySmsBundle\DependencyInjection\Factory\Gateway\YunxinFactory
    tags:
      - { name: akanunov_easy_sms.gateway_factory }

  akanunov_easy_sms.gateway_factory.yunzhixun:
    class: Akanunov\EasySmsBundle\DependencyInjection\Factory\Gateway\YunzhixunFactory
    tags:
      - { name: akanunov_easy_sms.gateway_factory }